# Makefile for my renderer library PaCaLib
# This is the Linux implementation
#

NAME                 =  PaCaLib_Linux
VERS_MAJOR           =  0
VERS_MINOR           =  1

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

BASE_LIBRARIES       =  pangocairo

include $(SCRIPTDIR)/makelib

